services:
  frontend:
    container_name: kupipodariday-frontend
    image: kupipodariday-frontend
    restart: always
    ports:
      - 8080:80
    networks:
      - external

  backend:
    container_name: kupipodariday-backend
    image: kupipodariday-backend
    restart: always
    env_file: .env
    ports:
      - 4000:3000
    networks:
      - internal

  postgres:
    container_name: kpd-postgres
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - kupipodariday_data:/data/postgres_data
    networks:
      - internal

  adminer:
    container_name: postgres-adminer
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - internal

volumes:
  kupipodariday_data:

networks:
  internal:
  external: