services:
  frontend:
    container_name: kupipodariday-frontend
    image: tatyanare/kupipodariday-frontend:1.0.1-alpine
    restart: always
    ports:
      - 8081:80
    networks:
      - external

  backend:
    container_name: kupipodariday-backend
    image: tatyanare/kupipodariday-backend:1.0.1-alpine
    restart: always
    env_file: .env
    ports:
      - 4000:3005
    networks:
      - internal

  postgres:
    container_name: kpd-postgres
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - kupipodariday_data:/data/postgres_data
    networks:
      - internal

  adminer:
    container_name: postgres-adminer
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - internal

volumes:
  kupipodariday_data:

networks:
  internal:
  external:

